services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --reload

  redis:
    image: redis:7
    ports:
      - "6379:6379"
